# Generated by Django 3.2.5 on 2021-07-07 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('birth_date', models.DateTimeField()),
                ('place', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('dose', models.IntegerField()),
                ('spreedsheet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.spreadsheet')),
            ],
        ),
    ]
