# Generated by Django 3.2.5 on 2021-07-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='spreedsheet',
            new_name='spreadsheet',
        ),
    ]
