# Generated by Django 3.2.5 on 2021-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_spreedsheet_schedule_spreadsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
