# Generated by Django 3.2.5 on 2021-07-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_spreadsheet_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spreadsheet',
            old_name='release_date',
            new_name='date',
        ),
    ]
