# Generated by Django 3.2.5 on 2021-07-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_rename_release_date_spreadsheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='spreadsheet_line',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='spreadsheet_page',
            field=models.IntegerField(null=True),
        ),
    ]
