# Generated by Django 3.2.5 on 2021-07-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20210716_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotification',
            old_name='sentat',
            new_name='sent_at',
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='second_dose_sent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
