# Generated by Django 3.2.5 on 2021-07-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20210716_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='second_dose_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
