# Generated by Django 3.2.5 on 2021-07-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20210716_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
