# Generated by Django 3.2.5 on 2021-07-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_alter_emailnotification_birth_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailnotification',
            unique_together={('name', 'email', 'birth_date')},
        ),
    ]
