# Generated by Django 3.2.5 on 2021-10-04 02:23

from django.db import migrations, models


def update_notified_dose(apps, schema):
    EmailNotification = apps.get_model('schedule', 'EmailNotification')
    for en in EmailNotification.objects.filter(second_dose_sent=True):
        en.notified_dose = 2
        en.save()
    for en in EmailNotification.objects.filter(second_dose_sent=False, sent_at__isnull=False):
        en.notified_dose = 1
        en.save()

class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_emailnotification_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='notified_dose',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(update_notified_dose, lambda x,y: None),
    ]
